version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: linkedin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d linkedin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Fixed: Use correct database connection for Docker network
      - DATABASE_URL=postgresql+psycopg2://app:app@db:5432/linkedin
      - SECRET_KEY=dev-secret-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    ports:
      - "8000:8000"
    volumes:
      # Mount current directory for development
      - .:/app
      # Exclude node_modules and other unnecessary directories
      - /app/__pycache__
      - /app/.pytest_cache
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        python -c 'import time; time.sleep(10)' &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting FastAPI server...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: unless-stopped

volumes:
  db_data: