"""Initial migration with user, post, and reaction tables

Revision ID: 249eefd87b89
Revises: 7964f7183668
Create Date: 2025-09-16 11:34:56.653739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249eefd87b89'
down_revision: Union[str, None] = '7964f7183668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
