"""Initial migration with user, post, and reaction tables

Revision ID: 4d3e22439291
Revises: 249eefd87b89
Create Date: 2025-09-16 11:45:34.750385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3e22439291'
down_revision: Union[str, None] = '249eefd87b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
