"""Initial migration with user, post, and reaction tables

Revision ID: 4f636d08f3b3
Revises: 4d3e22439291
Create Date: 2025-09-16 11:49:22.127684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f636d08f3b3'
down_revision: Union[str, None] = '4d3e22439291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
