"""Initial migration with user, post, and reaction tables

Revision ID: 7964f7183668
Revises: 
Create Date: 2025-09-16 02:33:42.466215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7964f7183668'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', name='post_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_second', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_post_owner_status_time', ['owner_id', 'status', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index('ix_post_scheduled_status', ['scheduled_at', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_status'), ['status'], unique=False)

    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('like', 'praise', 'empathy', 'interest', 'appreciation', name='reaction_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_index('ix_reaction_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_post_id'), ['post_id'], unique=False)
        batch_op.create_index('ix_reaction_post_type', ['post_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_type'))
        batch_op.drop_index('ix_reaction_post_type')
        batch_op.drop_index(batch_op.f('ix_reaction_post_id'))
        batch_op.drop_index('ix_reaction_created_at')

    op.drop_table('reaction')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_status'))
        batch_op.drop_index('ix_post_scheduled_status')
        batch_op.drop_index(batch_op.f('ix_post_scheduled_at'))
        batch_op.drop_index('ix_post_owner_status_time')
        batch_op.drop_index(batch_op.f('ix_post_owner_id'))
        batch_op.drop_index(batch_op.f('ix_post_id'))
        batch_op.drop_index('ix_post_created_at')

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    # ### end Alembic commands ###
